# Generated by Django 4.2.4 on 2023-08-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='details',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='details',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
